export const FETCH_BEER_REQUEST = "FETCH_BEER_REQUEST";
export const FETCH_BEER_SUCCESS = "FETCH_BEER_SUCCESS";
export const FETCH_BEER_FAILURE = "FETCH_BEER_FAILURE";

export const FETCHBYID_BEER_REQUEST = "FETCHBYID_BEER_REQUEST";
export const FETCHBYID_BEER_SUCCESS = "FETCHBYID_BEER_SUCCESS";
export const FETCHBYID_BEER_FAILURE = "FETCHBYID_BEER_FAILURE";
